[build-system]
requires = ["setuptools>=42"]
include-package-data = true
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
HSIBandSelection = ["*.txt"]
"HSIBandSelection.Data" = ["*.rst"]